# vim:ft=ansible:
---
# This Playbook will install redis 

- name: Install jupyter by pip
  pip: name={{ item }} state=present
  sudo: yes
  with_items:
    - jupyter
    - notebook
    - ipywidgets
    - ipyparallel 

- name: Generate Jupyter configuration
  shell: jupyter notebook --generate-config -y

- name: Generate IPython configuration 
  shell: ipython profile create

#- name: Update matplotlib fontList cache
#  file: src=/home/{{ user }}/.cache/matplotlib/fontList.cache 
#        state=absent
#  ignore_errors: yes

#- name: Config matplotlib
#  template: src=matplotlibrc.j2 dest=/home/{{ user }}/.config/matplotlib/matplotlibrc
#  ignore_errors: yes

- name: Config jupyter server
  template: src=jupyter_notebook_config.j2 dest=/home/{{ user }}/.jupyter/jupyter_notebook_config.py
  ignore_errors: yes

- name: Config IPython matplotlib
  template: src=ipython_kernel_config.j2 dest=/home/{{ user }}/.ipython/profile_default/ipython_kernel_config.py
  ignore_errors: yes
