# vim:ft=ansible:
---
# This Playbook will install redis 

- name: Install python data science dependencies
  apt: name={{ item }}
  sudo: yes
  with_items:
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-pandas
    - python-pil
    - python-scikits-learn
    - python-scikits.statsmodels
    - libpng-dev 
    - libjpeg8-dev 
    - libfreetype6-dev 
    - python-dev 
    - libsys-cpu-perl 
    - pcf2bdf 
    - tex-gyre 
    - ttf-bitstream-vera 
    - tv-fonts 
    - xfonts-traditional
    - pkg-config

- name: Install dependencies by pip
  pip: name={{ item }} state=present
  sudo: yes
  with_items:
    - scikit-learn
    - matplotlib
    - sympy
    - seaborn
    - patsy
    - statsmodels
    - networkx
    - ipythonblocks
    - plotly
    - dask
    - cython
    - blaze
    - odo
    - pandas
    - numpy
    - scipy
    - matplotlib
    - qgrid
