# vim:ft=ansible:
---
# This Playbook will install all basic tools on all machines

- name: Clean up /tmp
  mount: name=/tmp state=unmounted src=none fstype=none 
  ignore_errors: yes

#- name: Update the apt index
#  apt: update_cache=yes cache_valid_time=3600
#  sudo: yes

- name: Upgrade all packages
  apt: update_cache=yes cache_valid_time=3600 upgrade=yes
  become: yes

- name: build-essential
  apt: pkg=build-essential state=present update_cache=yes cache_valid_time=3600
  become: yes

- name: Install basic tools
  apt:
    name: ['language-pack-en', 'htop', 'exuberant-ctags', 'git', 'tree', 'vim', 'iperf'] 
    update_cache: yes
  become: yes

- name: Setup time zone
  shell: timedatectl set-timezone {{ timezone }}
  become: yes

- name: Create the Downloads directory for all machines
  file: path=/home/ubuntu/Downloads state=directory mode=0755 owner=ubuntu

- name: Config git email  
  shell: git config --global user.email {{ git_email }}

- name: Config git email  
  shell: git config --global user.name {{ git_name }}
