# vim:ft=ansible:
---
# This Playbook will install Java 11 

- name: Install Oracle Java 11 install python-software-properties
  apt: name=software-properties-common state=latest
  sudo: yes

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:linuxuprising/java'
  sudo: yes

- name: Accept Java 11 License
  debconf: name='oracle-java11-installer-local' 
           question='shared/accepted-oracle-license-v1-1' 
           value='true' 
           vtype='select'
  sudo: yes

- name: Install Oracle Java 11
  apt:
    name: ['oracle-java11-installer-local', 'ca-certificates', 'oracle-java11-set-default-local'] 
    state: latest
  sudo: yes

- name: Setup JAVA_HOME
  lineinfile: dest=/home/ubuntu/.zshrc line="export JAVA_HOME=/usr/lib/jvm/java-11-oracle/"

- name: Setup PATH
  lineinfile: dest=/home/ubuntu/.zshrc line="PATH=$PATH:/usr/lib/jvm/java-11-oracle/jre/bin/"
