# vim:ft=ansible:
---
# This Playbook install the latest Python

- name: Install python kits
  apt: 
    name: ['python-pip', 'python3-pip', 'python-dev']
    state: latest 
    update_cache: yes
  become: yes 

- name: Upgrade pip
  pip: name=pip extra_args=--upgrade
  become: yes 

- name: Upgrade pip3
  pip: name=pip extra_args=--upgrade executable=pip3
  become: yes 
