# vim:ft=ansible:
---
# This Playbook install the latest Python

- name: Install python kits
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-pip
    - python3-pip
    - python-dev
  become: yes 

- name: Fix potential pip2 and pip3 mixup
  shell: python3 -m pip install -U --force-reinstall pip
  become: yes

- name: Fix potential pip2 and pip3 mixup
  shell: python2 -m pip install -U --force-reinstall pip
  become: yes

- name: Upgrade pip
  pip: name=pip extra_args=--upgrade
  become: yes

- name: Upgrade pip3
  pip: name=pip extra_args=--upgrade executable=pip3
  become: yes
