# vim:ft=ansible:
---
# This Playbook will install the latest SBT

- name: Add SBT source
  shell: echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  sudo: yes

- name: Add SBT repo key 
  apt_key:
    id: 642AC823
    keyserver: hkp://keyserver.ubuntu.com:80
  sudo: yes

- name: Install SBT 
  apt: name=sbt state=latest update_cache=yes
  sudo: yes
