# vim:ft=ansible:
---
# This Playbook install the latest tmux

- name: Add latest tmux repo
  apt_repository: repo='ppa:pi-rho/dev'
  sudo: yes 
  
- name: Install tmux
  apt: name=tmux state=latest
  sudo: yes 

- name: Update config
  copy: src=/home/ubuntu/dotfiles/.tmux.conf dest=/home/ubuntu/
