# vim:ft=ansible:
---
# This Playbook will install all basic tools on all machines

- name: Install basic toolkits
  import_tasks: './install/basics.yml'

- name: Git clone dotfiles 
  import_tasks: './install/dotfiles.yml'

- name: Install tmux
  import_tasks: './install/tmux.yml'

- name: Install zsh
  import_tasks: './install/zsh.yml'

- name: Install python
  import_tasks: './install/python.yml'

- name: Install vim
  import_tasks: './install/vim.yml'

- name: Install Java 11 
  import_tasks: './install/java.yml'

- name: Install SBT
  import_tasks: './install/sbt.yml'

- name: Install Conda
  import_tasks: './install/conda.yml'
