# vim:ft=ansible:
---
# This Playbook runs all the common plays in the deployment

- name: Clean up /tmp
  mount: name=/tmp state=unmounted src=none fstype=none
  become: yes
  ignore_errors: yes

- name: Setup /mnt
  file:
    path: '/mnt'
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
  become: yes
  ignore_errors: yes

- name: Install toolchain
  import_tasks: install_toolchain.yml
  
- name: SSH configuration
  import_tasks: ssh_config.yml

- name: Setup env variables
  import_tasks: setup_env.yml

