# vim:ft=ansible:
---
# This Playbook will configure SSH

- name: Configure ssh_config
  lineinfile: dest=/etc/ssh/ssh_config line='    StrictHostKeyChecking no\n    UserKnownHostsFile=/dev/null'
  sudo: yes

#- name: Generate key
#  shell: ssh-keygen -f /home/{{ user }}/.ssh/id_rsa_local -t rsa -N ''
#  ignore_errors: yes

- name: Add key
  authorized_key: user={{ user }} key={{ pub_keys }}
