# vim:ft=ansible:
---
# This Playbook will install redis 

- name: Add latest Redis Repository
  apt_repository: repo='ppa:rwky/redis'
  sudo: yes

- name: Update the apt index
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install redis-server
  apt: name=redis-server
  sudo: yes

- name: Install redis-tools
  apt: name=redis-tools
  sudo: yes
